name: Getting Twrp CI

on:
  push:
    branches: [ "android-8.0", "android-8.1", "android-9.0", "android-12.1" ]
  pull_request:
    branches: [ "android-8.0", "android-8.1", "android-9.0", "android-12.1" ]  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make curl git wget

    - name: Show environment variables
      run: env
      
    - name: Get repo
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > repo
        chmod a+x repo
        sudo mv repo /usr/local/bin/

    - name: Initialize a shallow clone
      run: |
        mkdir twrp
        cd twrp
        repo init --depth=1 -u git://github.com/DereckySany/platform_manifest_twrp_omni.git -b twrp-8.0
      if: failure()

    - name: Sync up repo
      run: |
        cd twrp
        repo sync
      
    - name: List directory
      run: ls
