name: Getting Twrp CI

on:
  push:
    branches: [ "android-8.0", "android-8.1", "android-9.0", "android-12.1" ]
  pull_request:
    branches: [ "android-8.0", "android-8.1", "android-9.0", "android-12.1" ]  
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: apt-get install make curl git wget

    - name: install repo
      run: curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/bin/repo && chmod a+x /usr/bin/repo

    - name: initialize a shallow clone
      run: repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.0

    - name: sync up repo
      run: repo sync
      
    - name: list dir
      run: ls
