name: Getting Twrp CI

on:
  push:
    branches: [ "android-8.0", "android-8.1", "android-9.0", "android-12.1" ]
  pull_request:
    branches: [ "android-8.0", "android-8.1", "android-9.0", "android-12.1" ]  
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Delete failed workflow runs
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/actions/runs \
             | jq -r '.workflow_runs[] | select(.conclusion == "failure") | .id' \
             | xargs -I {} curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
             https://api.github.com/repos/${{ github.repository }}/actions/runs/{}
             
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y make curl git wget repo

    - name: Show environment variables
      run: env
      
#    - name: Get repo
#      run: |
#        curl https://storage.googleapis.com/git-repo-downloads/repo > repo
#        chmod a+x repo
#        sudo mv repo /usr/local/bin/

    - name: Initialize a shallow clone
      id: init
      run: |
        mkdir twrp
        cd twrp
        git config --global user.name ""${{ secrets.GIT_USER_NAME }}""
        git config --global user.email ""${{ secrets.GIT_USER_EMAIL }}""
        repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1 || echo "init_failed" > /tmp/err
      #repo init --depth=1 -u git://github.com/DereckySany/platform_manifest_twrp_omni.git -b twrp-8.0 || echo "init_failed" > /tmp/err

    - name: Check for errors
      run: |
        if [ -f /tmp/err ]; then
          echo "Error initializing the repository"
          exit 1
        fi

    - name: Sync up repo
      run: |
        cd twrp
        repo sync
      
    - name: List directory
      run: ls
